### ISSUE TITLE
Invalid arguments

### ISSUE THREAD

**Issue by songsammy** [log0/neural-style-painting#8]
Traceback (most recent call last):
  File "D:\py\neural-style-painting\ac.py", line 274, in <module>
    content_image = load_image(CONTENT_IMAGE)
  File "D:\py\neural-style-painting\ac.py", line 66, in load_image
    image = scipy.misc.imread(path)
AttributeError: module 'scipy.misc' has no attribute 'imread'

**Comment by songsammy** [comment]
I mean , the format of arguments.

**Comment by impactcolor** [comment]
Same error... Did you fix this?  @songsammy

**Comment by impactcolor** [comment]
Never mind error is because it requires pillow @songsammy

**Comment by songsammy** [comment]
ThankU
